### PR TITLE
Fixed bug in result Dockerfile

### PR DESCRIPTION
**Pull request by FlyingBird95**
I ran the command:

`docker-compose up`

and it didn't worked because there was an error in the Dockerfile of result.

Therefore, I fixed it!

### CODE REVIEW

**Comment by BretFisher** [comment]
Can you give us the error you're seeing and your environment setup? I've not seen this issue before, so I'm assuming it's due to a unique environment.

**Comment by BretFisher** [comment]
I've built master on macOS and Windows 10 Pro (both with Docker Desktop 19.03.1) and don't get this error.

**Comment by BretFisher** [comment]
OK, my research shows that this error is caused by a long-standing on-and-off-again npm+alpine bug.  [npm has fixed it in 6.11](https://github.com/npm/uid-number/issues/7), but we'll need to wait for that to be default in upstream official images, so choices are:

1. Accept this PR workaround that slightly lowers the security of npm
2. Install the newer npm in this image ourselves (which to get it installed, may still require this workaround)
3. Use debian slim version of this image, which I've tested and works. It also prevents multiple other node/npm issues I've seen over the years with using `node:alpine`. 

Since this is an example app that we would rather have minimal future issues with, I'm recommending the 3rd option and have added that to my `result` update PR #140 

Once that's accepted we can close this issue. Thanks for the heads up @FlyingBird95

**Comment by JimCodified** [comment]
Verifying that PR #140 fixed this issue and we're OK to close this one? @FlyingBird95 @BretFisher

**Pull request closed without merging**
