### PR TITLE
Removed volume mounts from compose files

### PR DESCRIPTION
**Pull request by larryclaman**
removed volume mounts per issue #148

### CODE REVIEW

**Comment by karunpabbi** [comment]
Need to have authentication part

**Comment by JimCodified** [comment]
I think we'll want to have one Compose file that does still have the volume mounts, specifically to show the dev use case. What I'd propose is copying the current `docker-compose-simple.yml` to `docker-compose-dev.yml` and then we can take the mounts out of the other files.

**Comment by BretFisher** [comment]
Sorry no one responded a year ago. This is a big commit set, and I'm not sure what the focus is anymore of this 55-commit PR. I'm going to close this, but if you'd like to submit a small PR, please open a ticket for a problem you'd like to solve first, and that way we can ensure the PR focuses on a single fix, thanks!

**Comment by larryclaman** [comment]
My bad... I had completely forgotten about this PR, and recently I started using my fork as the basis for some experimentation.  My apologies that these recent edits got pushed back into the PR

**Pull request closed without merging**
